name: Build a native image
on:
  push:
    branches:
      - main
jobs:
    build-jar:
        runs-on: ubuntu-20.04
        steps:
            - name: Build a Java project using Maven
              uses: microsoft/nubesgen-actions/gitops-build-java-maven@v0.4.0
    build-unix-images:
        needs: [ build-jar ]
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest]
            include:
                - os: 'ubuntu-latest'
                  label: 'linux'
                - os: 'macos-latest'
                  label: 'mac'
        steps:
            - name: Download application package
              uses: actions/download-artifact@v2
              with:
                  name: package
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@5.0
              with:
                  graalvm-version: '21.3.0.java11'
            - name: Install native-image
              run: |
                  gu install native-image
            - name: Build native image
              run: native-image --enable-url-protocols=https --static -jar nubesgen-cli-*.jar
            - name: Temporarily save package
              uses: actions/upload-artifact@v2
              with:
                  name: ${{matrix.label}}-binary
                  path: 'nubesgen-cli-*'
                  retention-days: 1
    build-windows-image:
        needs: [ build-jar ]
        runs-on: windows-latest
        steps:
            - name: Download application package
              uses: actions/download-artifact@v2
              with:
                  name: package
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@5.0
              with:
                  graalvm-version: '21.3.0.java11'
            - name: Install native-image
              run: |
                  gu.cmd install native-image
            - name: 'Install Visual C Build Tools Workload for Visual Studio 2017 Build Tools'
              run: |
                  choco install visualstudio2017-workload-vctools
            - name: 'Set up  Visual C Build Tools Workload'
              shell: cmd
              run: |
                  call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
            - name: Build native image
              run: native-image --enable-url-protocols=https -jar nubesgen-cli-*.jar
            - name: Temporarily save package
              uses: actions/upload-artifact@v2
              with:
                  name: window-binary
                  path: 'nubesgen-cli-*.exe'
                  retention-days: 1
