name: Build a native image
on:
  push:
    branches:
      - main
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@5.0
              with:
                graalvm-version: '21.3.0.java17'
            - name: Cache local Maven repository
              uses: actions/cache@v2
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                restore-keys: |
                  ${{ runner.os }}-maven-
            - name: Build Java package
              run: mvn package
            - name: Test GraalVM installation
              run: java -version
            - name: Install native-image
              run: |
                echo
                gu install native-image
            - name: Build native image
              run: native-image --enable-url-protocols=https --static -jar target/nubesgen-cli-*.jar
