name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
    build-jar:
        name: 'Build JAR package'
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Java
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: '11'
                  check-latest: false
                  cache: 'maven'
            - name: Build with Maven
              run: 'mvn package'
            - name: Temporarily save package
              uses: actions/upload-artifact@v2
              with:
                  name: java-binary
                  path: |
                      target/*.jar
                      !target/original-*.jar
                  retention-days: 1
    build-native-images:
        name: 'Build native images using GraalVM'
        needs: [ build-jar ]
        runs-on: ${{ matrix.os_name }}
        strategy:
            matrix:
                include:
                    - image_name: linux
                      os_name: ubuntu-latest
                      install_command: gu install native-image
                      build_command: native-image --enable-url-protocols=https --static -jar nubesgen-cli-*.jar nubesgen-cli-linux
                    - image_name: macos
                      os_name: macos-latest
                      install_command: gu install native-image
                      build_command: native-image --enable-url-protocols=https -jar nubesgen-cli-*.jar nubesgen-cli-macos
                    - image_name: windows
                      os_name: windows-latest
                      install_command: gu.cmd install native-image && choco install visualstudio2017-workload-vctools && "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
                      build_command: native-image --enable-url-protocols=https -jar nubesgen-cli-*.jar nubesgen-cli-windows
        steps:
            - name: Download application package
              uses: actions/download-artifact@v2
              with:
                  name: java-binary
            - name: Install GraalVM
              uses: DeLaGuardo/setup-graalvm@5.0
              with:
                  graalvm-version: '21.3.0.java11'
            - name: Install native-image
              run: ${{ matrix.install_command }}
            - name: Build native image
              run: ${{ matrix.build_command }}
            - name: Temporarily save package
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.image_name }}-binary
                  path: |
                      nubesgen-cli-*
                      !*.txt
                      !*.jar
                  retention-days: 30
